#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SPEC_PATH="$APP_DIR/Project.yml"
DERIVED_DATA_PATH="${NOODLE_TPROXY_DERIVED_DATA_PATH:-$APP_DIR/.xcode-derived/noodle-app-dev}"
TEAM_ID="${NOODLE_TPROXY_DEVELOPMENT_TEAM:?set NOODLE_TPROXY_DEVELOPMENT_TEAM to your Apple Developer team ID (any personal Apple ID works for dev mode; check Xcode → Settings → Accounts)}"
CONTAINER_SIGNING_IDENTITY="${NOODLE_TPROXY_CONTAINER_SIGNING_IDENTITY:-Apple Development}"
EXT_SIGNING_IDENTITY="${NOODLE_TPROXY_EXTENSION_SIGNING_IDENTITY:-$CONTAINER_SIGNING_IDENTITY}"
CONTAINER_PROFILE_SPECIFIER="${NOODLE_TPROXY_CONTAINER_PROFILE_SPECIFIER:-}"
EXT_PROFILE_SPECIFIER="${NOODLE_TPROXY_EXTENSION_PROFILE_SPECIFIER:-}"
BUILD_VERSION="${NOODLE_TPROXY_CURRENT_PROJECT_VERSION:-$(date +%Y%m%d%H%M%S)}"

cd "$APP_DIR"
xcodegen generate --spec "$SPEC_PATH"

cmd=(
  xcodebuild
  -project Noodle.xcodeproj
  -scheme Noodle
  -configuration Debug
  -derivedDataPath "$DERIVED_DATA_PATH"
  -allowProvisioningUpdates
  NOODLE_TPROXY_DEVELOPMENT_TEAM="$TEAM_ID"
  NOODLE_TPROXY_CONTAINER_SIGNING_IDENTITY="$CONTAINER_SIGNING_IDENTITY"
  NOODLE_TPROXY_EXTENSION_SIGNING_IDENTITY="$EXT_SIGNING_IDENTITY"
  NOODLE_TPROXY_CURRENT_PROJECT_VERSION="$BUILD_VERSION"
)

if [[ -n "$CONTAINER_PROFILE_SPECIFIER" ]]; then
  cmd+=(NOODLE_TPROXY_CONTAINER_PROFILE_SPECIFIER="$CONTAINER_PROFILE_SPECIFIER")
fi
if [[ -n "$EXT_PROFILE_SPECIFIER" ]]; then
  cmd+=(NOODLE_TPROXY_EXTENSION_PROFILE_SPECIFIER="$EXT_PROFILE_SPECIFIER")
fi

cmd+=(clean build)
"${cmd[@]}"
